#include "Table.cpp"
#include <iostream>

using namespace std;

int main(){
    Table t(4);
    t.show();
    cout << "#############\n";
    t.add();
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    t.left();
    t.show();
    cout << "#############\n";
    t.right();
    t.show();
    cout << "#############\n";
    


}